#!/usr/bin/perl
# Copyright (c) 2008 Lara Stoltenow <penma@penma.de>
# License: WTFPL
use strict;
use warnings;
use bignum;
use Getopt::Std;

my %opts = (v => 0);
getopts('v', \%opts);
my $e = "a(" . join(",", @ARGV) . ")";

while (1)
{
	$opts{v} && print "\e[1;31m" . length($e) . "\e[m   $e\n";
	
	if ($e =~ /a\(([0-9]+),([0-9]+)\)/)
	{
		my $r;
		
		$r = "a(" . ($1 - 1) . ",a($1," . ($2 - 1) . "))";
		$r = "a(" . ($1 - 1) . ",1)" if ($2 == 0);
		$r = $2 + 1 if ($1 == 0);
		$r = $2 + 2 if ($1 == 1);
		$r = 2 * $2 + 3 if ($1 == 2);
		$r = 8 * 2 ** $2 - 3 if ($1 == 3);
		
		$e =~ s/a\($1,$2\)/$r/g;
	}
	else
	{
		$opts{v} || print "$e\n";
		last;
	}
}
