#!/usr/bin/perl
use MIME::Base64;
unless (@ARGV == 0 or ($ARGV[0] eq '-d' and @ARGV == 1)) {
    if ($ARGV[0] eq '-d') {
        print decode_base64($ARGV[1]);
    } else {
        print encode_base64($ARGV[0]);
}} else {
    if ($ARGV[0] eq '-d') {
        while (!eof(STDIN)) {
            print decode_base64(<STDIN>);
    }} else {
        my $input;
        while (!eof(STDIN)) {
            $input .= <STDIN>;
        }
        print encode_base64($input);
}}
