#!/usr/bin/env perl
# Copyright (C) 2008 Maximilian Gaß <mxey@cloudconnected.org>
# Licensed under GPLv3 or later version

# Resembles the speaking of the flamingo in Max Payne 2:
# "Mirrors are more fun than television" becomes
# "mirrorS arE morE fuN thaN televisioN"

use strict;
use warnings;

while(<>) {
	chomp;
	s/(\w*)(\w)/\L$1\E\u$2/g;
	print;
}
