#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Std;

my @marks = ('', '.'x(int(rand(3))+1), '!');
my %options;
my $char = 'h';
my $end = 'm';

getopts('ugr', \%options);

if ($options{u}) {
	push(@marks, '…');
}
if ($options{g}) {
	$char = 'gr';
} elsif ($options{r}) {
	$char = 'hr';
} else {
	if (@ARGV) {
		$char = shift;
		$end = substr($char, -1, 1);
	}
}
print(($char.$end x(int(rand(4))+1))x(int(rand(12)/10)+1).$marks[rand@marks]."\n")

__END__

=head1 NAME

hm - say hm

=head1 SYNOPSIS

B<hm> [ B<-u> ] [ B<-g>|B<-r>|I<string> ]

=head1 DESCRIPTION

B<hm> says 'hm' in different ways, such as 'hmm...', 'hm!' or 'hmmhmm'

It does this by taking a string (by default 'hm'), repeating it's last character
some times, maybe doing all that again, and appending some dots or so
to the end

=head1 OPTIONS

=over

=item B<-u>

Unicode. Adds the unicode variant of '...' to the possible word ends.

=item B<-g>

Use 'grm' as string

=item B<-r>

Use 'hrm' as string

=item I<string>

Use I<string> as string

=back

=head1 AUTHOR

Daniel Friesel <derf@derf.homelinux.org>

L<https://derf.homelinux.org/~derf/code/hm>

=head1 LICENSE

  0. You just DO WHAT THE FUCK YOU WANT TO.
