#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Std;

my @marks = ('', '.'x(int(rand(3))+1), '!');
my %options;
my $char;

getopts('ugr', \%options);

if ($options{u}) {
	push(@marks, '…');
}
if ($options{g}) {
	$char = 'gr';
} elsif ($options{r}) {
	$char = 'hr';
} else {
	$char = shift || 'h';
}
print(($char.'m'x(int(rand(4))+1))x(int(rand(12)/10)+1).$marks[rand@marks]."\n")

__END__

=head1 NAME

hm - say hm

=head1 SYNOPSIS

B<hm> [ B<-u> ] [ B<-g>|B<-r>|I<string> ]

=head1 DESCRIPTION

B<hm> says 'hm' in different ways, such as 'hmm...', 'hm!' or 'hmmhmm'

It does this by taking a string (by default 'h'), adding some 'm's, 
maybe a repetition of all that, and then other fancy stuff

=head1 OPTIONS

=over

=item B<-u>

Unicode. Adds the unicode variant of '...' to the possible word ends.

=item B<-g>

Use 'gr' as string, producing output like 'grm'

=item B<-r>

Use 'hr' as string, producing output like 'hrm'

=item I<string>

Use I<string> as string

=back

=head1 AUTHOR

Daniel Friesel <derf@derf.homelinux.org>

=head1 LICENSE

  0. You just DO WHAT THE FUCK YOU WANT TO.
