#!/usr/bin/env perl
# Copyright (c) Maximilian Gaß <mxey@cloudconnected.org>
# License: WTFPL
use strict;
use warnings;
use LWP::UserAgent;

if (!scalar(@ARGV)) {
    print STDERR "Usage: $0 name [name ...]\n";
    exit 1;
}

my $ua = new LWP::UserAgent;

for my $nick (@ARGV) {
	my $req = new HTTP::Request(POST => "http://www.bongster.de/scripte/schwulometer.pl");
	$req->content_type("application/x-www-form-urlencoded");
	$req->content("nick=$nick");
	$req->header(Referer => "http://www.bongster.de/scripte/schwulometer.pl");
	
	my $res = $ua->request($req);
	if (!$res->is_success) {
		die("Could not get site: $res->status_line - dying");
	}
	
    if ($res->content =~ m#<b>([0-9]{1,2},[0-9]{1,2}%)</b>#m) {
        if (@ARGV > 1) {
            print "$nick:\t";
        }
        print "$1\n";
    } else {
        print STDERR "Could not find percent\n";
    }
}

