#!/usr/bin/env perl
# By mxey the great, the nightmare of kernels.
use strict;
use warnings;
use LWP::Simple;

if (!scalar(@ARGV)) {
    print STDERR "Usage: $0 name [name ...]\n";
    exit 1;
}

my $content;

for my $nick (@ARGV) {
    $content = get('http://bongster.de/scripte/schwulometer.pl?nick='
     . $nick) or die "Could not get site";

    if ($content =~ m#<b>([0-9]{1,2},[0-9]{1,2}%)</b>#m) {
        if (@ARGV > 1) {
            print "$nick:\t";
        }
        print "$1\n";
    } else {
        print STDERR "Could not find percent\n";
    }
}
