#!/usr/bin/perl -w
# License: Public Domain.
use strict;

my $word = shift // usage();
my $count = shift // usage();
my $delay = shift // usage();
my $vdelay = shift // ($delay / 10);

use Curses;
use Time::HiRes qw(sleep);

print_manmachine($word);

#####

sub usage
{
	print "$0 word count delay [ vdelay ]\n";
	print "\tword\tWord to print\n";
	print "\tcount\tHow many times to print the word in one row\n";
	print "\tdelay\tHow long to sleep between printing rows\n";
	print "\tvdelay\tHow long to sleep between vertical prints\n";
	exit 1;
}

sub print_manmachine
{
	my ($word) = @_;
	initscr();
	curs_set(0);
	start_color();
	init_pair(1, COLOR_RED, COLOR_BLACK);

	my @letters = split //, $word;

	for(my ($i, $j) = (0, scalar @letters-1); $i < scalar @letters; ++$i, --$j)
	{
		move($j,$i);
		for(my$d=$count;$d--;)
		{
			printw($word);
			printw(" " x (scalar @letters-1));
		}
		refresh();
		sleep($delay);
	}
	for(my $i = 0; $i < scalar @letters; ++$i)
	{
		for(my$f=$count;$f--;)
		{
			move($i, (((scalar @letters)*2)-1)*($f+1)-(scalar @letters));
			attron(COLOR_PAIR(1));
			printw($letters[$i]);
			attroff(COLOR_PAIR(1));
		}
		refresh();
		sleep($vdelay);
	}
	endwin();
}

# Written by Zaba
