#!/usr/bin/env python
# Copyright (c) 2008 Maximilian Gaß <mxey@cloudconnected.org>
# Licensed under WTFPL

# Perhaps the purpose of this script might be a bit confusing, so..
#
# Python has an os module, and path submodule in that.  And the path submodule
# imports os module again.  This script is intended to check how deep one can
# recurse.

import os

def endless():
    i = 0
    while True:
        yield i
        i += 1

for i in endless():
    code = "os.path. " * i
    code += "os.path"
    print "Round %s" % i
    eval(code)
