#!/bin/bash
c[0]=.;c[1]=,;c[2]=\;;c[3]=:;export i=0;export j=.;while
true;do echo -ne "|$j\n";export l=`echo "|${j}">l;rev l`;
read k;if [[ $k != $l ]]; then echo "LOSER";break;fi;
export j=${j}${c[(( $RANDOM % 4 + 1 ))]};done
# Written by Zaba
