#!/usr/bin/env perl
# Written by Zaba in less than 10 minutes
# Yes, this is a quick and ugly hack, and
# it was written to replace the old pong2
# in shell that was even uglier.
# License: Public Domain.
use strict;
use warnings;

$| = 1;

my$c="|.";print"$c\n";while(<>){
chomp;die'You lose'unless(reverse
eq$c);$c.=('.',',',':',';')[rand
(4)];print"$c\n"}
