#!/usr/bin/env perl
# Copyright (c) 2008 Lara Stoltenow <penma@penma.de>
# Licensed under WTFPL

use strict;
use warnings;
use Time::HiRes qw(sleep);

my ($MINDIST, $MAXDIST, $LINES) = (2, 10, 12);

$| = 1;

while (1)
{
	for my $seldist ($MINDIST..$MAXDIST)
	{
		print "\e[2J";
		for my $dist ($MINDIST..$MAXDIST)
		{
			for my $angle (1..$LINES)
			{
				$angle = $angle * 3.141592653528 * 2 / $LINES;
				my $X = cos($angle) * $dist * 4 + 40;
				my $Y = sin($angle) * $dist + 12.5;
				printf("\e[%2\$d;%1\$dH%3\$s", $X, $Y, $dist == $seldist ? "\e[1;32m*\e[m" : ".")
					if (($X > 10 and $X < 70) and ($Y > 5 and $Y < 20));
			}
		}
		sleep(0.05);
	}
	sleep(0.6);
}
