#!/usr/bin/perl
use MIME::Base64;
unless (@ARGV == 0) {
    print &_rot13($ARGV[0])."\n";
} else {
    my $input;
    while (!eof(STDIN)) {
        $input .= <STDIN>;
    }
    print &_rot13($input);
}

sub _rot13 {
    my $string = shift;
    $string =~ tr/[a-mA-Mn-zN-Z]/[n-zN-Za-mA-M]/;
    return $string;
}
