#!/usr/bin/perl
# xstrobo - Adaption of the famous Augenkrebs Flash movies on the Internet
# using xgamma
# Made 2007 Lars Stoltenow <penma@penma.de>
#
# This program is released into Public Domain, or, if this is not possible in
# your country, unlimited permission to use, change, or redistribute is granted
# to the extent permitted by applicable law.
# 
# No warranty for eye damage!
use strict;
use Time::HiRes;

print STDERR "xstrobo 0.2\n";
print STDERR "No warranty for eye damage!\n";

# Save original gamma
$_ = qx(xgamma 2>&1);
/-> Red  ?([^, ]+), Green  ?([^, ]+), Blue  ?([^, ]+)/;
my ($ORGamma, $OGGamma, $OBGamma) = ($1, $2, $3);

$SIG{"TERM"} = $SIG{"INT"} = sub { system("xgamma -q -rgamma $ORGamma -ggamma $OGGamma -bgamma $OBGamma"); exit(1); };

my (@RGamma, @GGamma, @BGamma, @Sleep);

while (scalar(@ARGV) > 0)
{
	push(@RGamma, shift(@ARGV));
	push(@GGamma, shift(@ARGV));
	push(@BGamma, shift(@ARGV));
	push(@Sleep, shift(@ARGV));
}

print STDERR "SIGINT (Ctrl-C) or SIGTERM to cancel, will restore old values\n";

while (1)
{
	for (0..(scalar(@RGamma) - 1))
	{
		system("xgamma -q -rgamma $RGamma[$_] -ggamma $GGamma[$_] -bgamma $BGamma[$_]");
		Time::HiRes::usleep($Sleep[$_]);
	}
}