#!/usr/bin/env perl
while (<>)
{
	chomp;
	/(.) (.)/;
	my $state = ($2 eq "0" ? "off" : "on");
	my $led = ($1 eq "1" ? "0" : ($1 eq "2" ? $1 : "7"));
	system("sh -c \"echo " . $led . " " . $state . " > /proc/acpi/ibm/led\"");
}
