#!/usr/bin/env perl
use strict;
use warnings;

sub write_to_led {
	open(LED, '>', '/proc/acpi/ibm/led') or die("Cannot open /proc/acpi/ibm/led: $!");
	print LED shift;
	close(LED);
}

while (<>) {
	chomp;
	/(.) (.)/;
	my $state = ($2 eq "0" ? "off" : "on");
	my $led = ($1 eq "1" ? "0" : ($1 eq "2" ? $1 : "7"));
	write_to_led("$led $state");
}
